### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cmnord** [techx/arduino-track#1]
Thoughts on (c) Claire Nord, Noah Moroze, Kye Burchard, and Rinik Kumar? @kyeb @nmoroze @rk9109

**Comment by nmoroze** [comment]
I'm open to using a more permissive license rather than "All Rights Reserved", maybe some Creative Commons variant for content and MIT for code? 

Although, if we care about being specific about licensing maybe we should also check that our assets (code from the starter kit, random images and stuff) are all licensed so that we can use them.

**Comment by kyeb** [comment]
I would also be happy making it as permissive as possible. I think most of the code here is general/introductory enough that you can find the exact same code licensed in totally different ways, depending on where you look, and ours is even a bit different from those (I think). 

Not sure about images though.

**Comment by cmnord** [comment]
Only @kyeb's project code is original, I think. All the rest are Arduino examples, AFAIK.

**Comment by kyeb** [comment]
I briefly looked through, and I think that's correct - all public domain, or stuff that I wrote (which I'm 100% happy to go to MIT license or similar).

**Comment by cmnord** [comment]
blink, fade: "This example code is in the public domain."
rgb: elegoo ??
button: "This example code is in the public domain."
photoresistor: kye
lcd: elegoo ??
reaction game: kye

**Comment by cmnord** [comment]
I re-downloaded all the Elegoo libraries and they don't mention a license anywhere.

**Comment by kyeb** [comment]
We could also rewrite those two examples to give a different demonstration, so we're not using elegoo code?

**Comment by cmnord** [comment]
I just emailed Elegoo to ask them about their software licenses as well.

**Comment by cmnord** [comment]
> We could also rewrite those two examples to give a different demonstration, so we're not using elegoo code?

I don't want to put in more work than necessary 😛  let's just assume the Elegoo code is okay to include because they make it available to download [here](https://www.elegoo.com/tutorial/Elegoo%20Super%20Starter%20Kit%20for%20UNO%20V1.0.2019.09.17.zip)?
